mysql:
  build: mysql
  container_name: vika-mysql
  environment:
    MYSQL_USER: vika
    MYSQL_PASSWORD: 123456
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: vika_logic
  volumes_from:
    - datastore
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: vika-phpmyadmin
  links:
    - mysql
  environment:
    PMA_HOST: mysql
    PMA_PORT: 3306
  ports:
    - '8080:80'
datastore:
  image: busybox
  volumes:
    - /var/lib/mysql
php:
  build: php
  container_name: vika-container
  ports:
    - '80:80'
  links:
    - mysql
  volumes:
    - ./php/src:/var/www/html